-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 11:02:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistematmbndcimc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistematmbndcimc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistematmbndcimc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistematmbndcimc` ;

-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`usuarios` (
  `id` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  `email_verificado` TINYINT(1) NOT NULL DEFAULT '0',
  `ultimo_login` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `bloqueado_ate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `tentativas_login` INT NOT NULL DEFAULT '0',
  `role` ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_email_key` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`dados_corporais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`dados_corporais` (
  `idDados` VARCHAR(36) NOT NULL,
  `idUsuario` VARCHAR(191) NOT NULL,
  `peso_kg` DECIMAL(10,2) NOT NULL,
  `altura_cm` DECIMAL(5,2) NOT NULL,
  `genero` ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
  `idade` INT NOT NULL,
  `nivel_atividade` ENUM('Sedentario', 'Leve', 'Moderado', 'Intenso', 'MuitoIntenso') NOT NULL,
  `data_atualizacao_dados` DATETIME(3) NOT NULL,
  `data_registro_Inicial` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idDados`),
  UNIQUE INDEX `dados_corporais_idUsuario_key` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `dados_corporais_idUsuario_fkey`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`calculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`calculos` (
  `idCalculo` VARCHAR(36) NOT NULL,
  `idDados` VARCHAR(191) NOT NULL,
  `imc` DECIMAL(10,2) NOT NULL,
  `tmb` DECIMAL(10,2) NOT NULL,
  `ndc` DECIMAL(10,2) NOT NULL,
  `data_calculo` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `data_atualizacao_calculo` DATETIME(3) NOT NULL,
  PRIMARY KEY (`idCalculo`),
  INDEX `calculos_idDados_idx` (`idDados` ASC) VISIBLE,
  CONSTRAINT `calculos_idDados_fkey`
    FOREIGN KEY (`idDados`)
    REFERENCES `sistematmbndcimc`.`dados_corporais` (`idDados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`email_verification_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`email_verification_tokens` (
  `id` VARCHAR(36) NOT NULL,
  `usuarioId` VARCHAR(191) NOT NULL,
  `expira_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `token_hash` VARCHAR(64) NOT NULL,
  `usado_em` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_verification_tokens_token_hash_key` (`token_hash` ASC) VISIBLE,
  INDEX `email_verification_tokens_expira_em_idx` (`expira_em` ASC) VISIBLE,
  INDEX `email_verification_tokens_usuarioId_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `email_verification_tokens_usuarioId_fkey`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`exercicios` (
  `idExercicio` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `caminho_video` VARCHAR(255) NULL DEFAULT NULL,
  `grupo_muscular` ENUM('Peito', 'Costa', 'Ombro', 'Braço', 'Antebraço', 'Coxa', 'Perna', 'Glúteos', 'Abdomen', 'Cardio') NOT NULL,
  PRIMARY KEY (`idExercicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`historico_corporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`historico_corporal` (
  `idHistorico` VARCHAR(36) NOT NULL,
  `idDados` VARCHAR(191) NOT NULL,
  `peso_kg` DECIMAL(10,2) NOT NULL,
  `altura_cm` DECIMAL(5,2) NOT NULL,
  `genero` ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
  `idade` INT NOT NULL,
  `nivel_atividade` ENUM('Sedentario', 'Leve', 'Moderado', 'Intenso', 'MuitoIntenso') NOT NULL,
  `imc` DECIMAL(10,2) NOT NULL,
  `tmb` DECIMAL(10,2) NOT NULL,
  `ndc` DECIMAL(10,2) NOT NULL,
  `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`idHistorico`),
  INDEX `historico_corporal_idDados_idx` (`idDados` ASC) VISIBLE,
  INDEX `historico_corporal_criado_em_idx` (`criado_em` ASC) VISIBLE,
  CONSTRAINT `historico_corporal_idDados_fkey`
    FOREIGN KEY (`idDados`)
    REFERENCES `sistematmbndcimc`.`dados_corporais` (`idDados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`password_reset_tokens` (
  `id` VARCHAR(36) NOT NULL,
  `token_hash` VARCHAR(64) NOT NULL,
  `usuarioId` VARCHAR(191) NOT NULL,
  `expira_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `usado_em` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `password_reset_tokens_token_hash_key` (`token_hash` ASC) VISIBLE,
  INDEX `password_reset_tokens_usuarioId_idx` (`usuarioId` ASC) VISIBLE,
  INDEX `password_reset_tokens_expira_em_idx` (`expira_em` ASC) VISIBLE,
  CONSTRAINT `password_reset_tokens_usuarioId_fkey`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`perfil` (
  `idPerfil` VARCHAR(36) NOT NULL,
  `fotoPerfil` VARCHAR(255) NULL DEFAULT NULL,
  `idUsuario` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `perfil_idUsuario_key` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `perfil_idUsuario_fkey`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`treinos` (
  `idTreino` VARCHAR(36) NOT NULL,
  `idCalculo` VARCHAR(191) NULL DEFAULT NULL,
  `objetivo` ENUM('Hipertrofia', 'Emagrecimento', 'Resistencia', 'Condicionamento') NOT NULL,
  `nivel` ENUM('Iniciante', 'Intermediario', 'Avancado') NOT NULL,
  `data_criacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `idUsuario` VARCHAR(191) NULL DEFAULT NULL,
  `is_oficial` TINYINT(1) NOT NULL DEFAULT '0',
  `titulo` VARCHAR(150) NOT NULL DEFAULT 'Novo Treino',
  PRIMARY KEY (`idTreino`),
  INDEX `treinos_idCalculo_idx` (`idCalculo` ASC) VISIBLE,
  INDEX `treinos_idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `treinos_idCalculo_fkey`
    FOREIGN KEY (`idCalculo`)
    REFERENCES `sistematmbndcimc`.`calculos` (`idCalculo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `treinos_idUsuario_fkey`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`treinos_exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`treinos_exercicios` (
  `idTreino` VARCHAR(191) NOT NULL,
  `idExercicio` VARCHAR(191) NOT NULL,
  `series` INT NOT NULL,
  `descanso_segundos` INT NOT NULL,
  `repeticoes` INT NOT NULL,
  `grupo_muscular` ENUM('Peito', 'Costa', 'Ombro', 'Braço', 'Antebraço', 'Coxa', 'Perna', 'Glúteos', 'Abdomen', 'Cardio') NOT NULL,
  `tipo` ENUM('Forca', 'Cardio', 'Alongamento', 'Mobilidade') NOT NULL,
  PRIMARY KEY (`idTreino`, `idExercicio`),
  INDEX `treinos_exercicios_idExercicio_idx` (`idExercicio` ASC) VISIBLE,
  CONSTRAINT `treinos_exercicios_idExercicio_fkey`
    FOREIGN KEY (`idExercicio`)
    REFERENCES `sistematmbndcimc`.`exercicios` (`idExercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `treinos_exercicios_idTreino_fkey`
    FOREIGN KEY (`idTreino`)
    REFERENCES `sistematmbndcimc`.`treinos` (`idTreino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
